#!/bin/bash -e

# Run on client: watch -d 'find /data -mmin -1 -ls;echo;find /var/lib/mysql -mmin -1 -ls;echo;find /etc/mysql -cmin -10 -ls'
# Run a continous tail on /var/log/mysql/error.log when it becomes available

MASTER_IP=10.0.2.10
CLIENT_IP=10.0.2.200

echo ------
echo Check that client can connect to master via mysql client, no firewall issues, or DO NOT PROCEED
read a


echo ------
echo Turn off mysql on client
read a
set +e
ssh $CLIENT_IP /etc/init.d/mysql stop
set -e

echo ------
echo Removing previous dumps made in the last 30 mins
read a
find /data/ -maxdepth 1 -type d -name '2012-*_*' -mmin -30 -exec rm -rfv {} \;

echo ------
echo Dump/backup innodb tables
read a
innobackupex /data/

echo ------
backup=$(find /data/ -maxdepth 1 -type d -mmin -10 | tail -1)
echo Apply logs to backup $backup
read a
innobackupex --apply-log $backup

echo ------
echo rsync root .my.cnf file
read a
rsync -avzP /root/.my.cnf $CLIENT_IP:/root/.my.cnf


echo ------
echo rsync /etc/mysql/my.cnf sample file
read a
rsync -avzP /etc/mysql/my.cnf $CLIENT_IP:/etc/mysql/my.cnf.sample


echo ------
echo rsync /etc/mysql/debian.cnf file
read a
rsync -avzP /etc/mysql/debian.cnf $CLIENT_IP:/etc/mysql/debian.cnf


echo ------
echo rsync backup to client $backup
read a
rsync -avzP $backup/ $CLIENT_IP:$backup/

echo ------
todaysdate=`date +\%Y-\%m-\%d-\%M`
backupdir=/data/backups/mysql/$todaysdate
echo On client, backup /var/lib/mysql to $backupdir
read a
ssh $CLIENT_IP mkdir -p $backupdir
ssh $CLIENT_IP rsync -avP /var/lib/mysql $backupdir

echo ------
echo On client, delete existing /var/lib/mysql contents and copy in new
read a
ssh $CLIENT_IP 'rm -rfv /var/lib/mysql/*'
ssh $CLIENT_IP rsync -avP $backup/ /var/lib/mysql/
ssh $CLIENT_IP chown -Rv mysql.mysql /var/lib/mysql

echo ------
echo Start up client mysql, please verify
ssh $CLIENT_IP service mysql start

echo ------
echo Set master data, please verify
# TODO: move password into config file
ssh $CLIENT_IP "ip=\`cat /var/lib/mysql/xtrabackup_binlog_info\`;set -- \$ip;mysql -e \"change master to master_host=\\\"$MASTER_IP\\\", MASTER_USER=\\\"replicant\\\", MASTER_PASSWORD=\\\"mypass\\\", MASTER_LOG_FILE=\\\"\$1\\\", MASTER_LOG_POS=\$2;\""

echo ------
echo Start the slave on the client and verify all is well
read a

echo ------
echo END
